spring:

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:h2:mem:customer-service;TRACE_LEVEL_FILE=0;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;MODE=MYSQL;
    username: sa
    password: 9527

    initialization-mode: always
    continue-on-error: false

    platform: h2
    schema: classpath:db/schema-h2-sys.sql,classpath:db/schema-h2-mbr.sql
    data: classpath:db/data-h2-sys.sql,classpath:db/data-h2-mbr.sql
    sql-script-encoding: utf-8
    separator: ;
