server:

  tomcat:
    min-spare-threads: 30      # 线程池的最小备用线程数，tomcat启动时的初始化的线程数
    max-threads: 1000          # 线程池的最大线程数
    max-connections: 5000      # 最大连接数
    accept-count: 2000         # 排队数
    connection-timeout: 5000ms # 最长等待时间

spring:

  # 数据源
  datasource:
    url: jdbc:mysql://${spring.redis.host}:3306/customer-service?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver # `com.mysql.cj.jdbc.Driver` for mysql5.7+

    # 1、hikari
    type: com.zaxxer.hikari.HikariDataSource # spring2.0以上默认就是hikari，这行配置可以省略
    hikari:
      #连接池名称，默认HikariPool-1
      pool-name: KevinHikariPool
      auto-commit: true
      #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 16
      #连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000
      #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 4
      #空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
      # 只有空闲连接数大于最大连接数且空闲时间(毫秒)超过该值，才会被释放
      idle-timeout: 500000
      #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 1200000
      connection-test-query: SELECT 1

    ## 2、druid
    #type: com.alibaba.druid.pool.DruidDataSource
    #druid:
    #  # pool strategy
    #  initial-size: 1
    #  max-active: 20
    #  min-idle: 1
    #  max-wait: 60000
    #  query-timeout: 90
    #  pool-prepared-statements: false
    #  max-pool-prepared-statement-per-connection-size: 20
    #
    #  # idle strategy
    #  test-while-idle: true
    #  min-evictable-idle-time-millis: 300000
    #  time-between-eviction-runs-millis: 60000
    #
    #  validationQuery: SELECT 'x'
    #  test-on-return: false
    #  test-on-borrow: false
    #  use-global-data-source-stat: true
    #  filters: stat,wall,slf4j
    #  filter:
    #    stat:
    #      merge-sql: false
    #      db-type: mysql
    #      slow-sql-millis: 2000
    #      log-slow-sql: true
    #    wall:
    #      db-type: mysql
    #      config:
    #        drop-table-allow: false
    #        delete-allow: true
    #      enabled: true
    #  stat-view-servlet:
    #    url-pattern: /druid/*
    #    login-username: admin
    #    login-password: admin
    #    reset-enable: false
    #    enabled: true

logging:
  config: ./config/log4j2-${spring.application.name}.xml

# 自定义属性文件
config:
  setting: ./config/setting-${spring.application.name}.properties
  captcha: ./config/captcha.properties
  oss: ./config/oss.properties
  ws: ./config/ws.properties
  sys: ./config/sys.properties
