server:

  tomcat:
    min-spare-threads: 30      # 线程池的最小备用线程数，tomcat启动时的初始化的线程数
    max-threads: 1000          # 线程池的最大线程数
    max-connections: 5000      # 最大连接数
    accept-count: 2000         # 排队数
    connection-timeout: 5000ms # 最长等待时间

spring:

  # 数据源
  datasource:
    # 注意mysql驱动8版本必须开启useUnicode=true
    url: jdbc:mysql://${spring.redis.host}:3306/customer-service?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: passowrd
    driver-class-name: com.mysql.jdbc.Driver # `com.mysql.cj.jdbc.Driver` for mysql5.7+
    type: com.zaxxer.hikari.HikariDataSource # spring2.0以上默认就是hikari，这行配置可以省略
    dynamic: # mybatis-plus 多数据源配置
      hikari:
        is-auto-commit: true
        max-pool-size: 16 # 最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
        connection-timeout: 60000 # 连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
        minimum-idle: 4 # 最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
        idle-timeout: 500000 # 空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。# 只有空闲连接数大于最大连接数且空闲时间(毫秒)超过该值，才会被释放
        max-lifetime: 1200000 # 连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
        connection-test-query: SELECT 1
      primary: master
      datasource:
        master:
          url: ${spring.datasource.url}
          username: ${spring.datasource.username}
          password: ${spring.datasource.password}
        # 从库数据源
        slave:
          # 从数据源开关/默认关闭
          lazy: true
          url: ${spring.datasource.url}
          username: ${spring.datasource.username}
          password: ${spring.datasource.password}

logging:
  config: config/log4j2-spring.xml

# 自定义属性文件
config:
  setting: config/setting.properties
  security: config/security.properties
  captcha: config/captcha.properties
  oss: config/oss.properties
  ws: config/ws.properties
  sys: config/sys.properties
