spring:

  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${spring.redis.host}:3306/customer-service?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    password: root
    username: root

    initialization-mode: always
    continue-on-error: false

    platform: mysql
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    sql-script-encoding: utf-8
    separator: ;
